# Generated by Django 3.0.5 on 2020-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type_id', models.IntegerField()),
                ('code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineWaterLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('model_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='machineproducttype',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
